### ISSUE TITLE
Version selector changes

### ISSUE THREAD

**Issue by lesserwhirls** [Unidata/unidata-jekyll-theme#15]
I'd like to propose a change to the version selector widget to support the concept of docsets.

## Version information json file - name and fetching

The version selector is designed around information contained within a json file of known location. Currently, the known location is a bit more complicated than it needs to be. Basically, we make the assumption that all documentation urls follow a pattern like:

`https://docs.unidata.ucar.edu/projectName/docsetVersion/docsetName/page.html`

So, the first path segment contains the name of the project. Using that, we can create the name of the json file following the pattern:

`projectName_doc_versions.json`

Then, we read the json file by issuing a `GET` request to `../../projectName_doc_versions.json`.

First, we don't really need the project name to prefix the json file, so I think we can simply rename it to be `version-info.json`.

Second, and more fundamentally, the url structure assumes the project has more than one docset (e.g. a user guide plus a developer gude), and that the url publishing structure does not use something more simple like `https://docs.unidata.ucar.edu/projectName/docsetVersion/page.html`. To correct this, we should fetch the version json file from `/projectName/version-info.json`.

## Content of json file

At a minimum, the version selector needs the following information to be defined inside the version information json file:

~~~json
{
  "releases" : [
    {
      "version" : "5.0",
      "include" : "1",
      "docURL" : "https://docs.unidata.ucar.edu/netcdf-java/5.0/userguide/index.html"
    }
  ]
}
~~~

Each release item indicates a:
 * version number (`version`)
 * visibility (`include=0` - do not show in version selector, `include=1` show in version selector)
 * url (`docURL`)

The `docURL` is used to construct everything in the URL except the page name when switching between versions. However, this does not support multiple docsets. For example:

<https://docs.unidata.ucar.edu/netcdf-java/6.0/developer/bufr_processing.html>

The version selector on the `developer` docset is finding and using the `userguide` url, as it's the only one defined in the version info json file (<https://docs.unidata.ucar.edu/netcdf-java/netcdf-java_doc_versions.json>

One thing we could do is extend the json file to either use `docURL` (if the documentation only has one docset) or `docURLs` (as a map) if the documentation contains multiple docsets. An example of what this could look like can be found at <https://docs.unidata.ucar.edu/netcdf-java/version-info.json>. Here we see both concepts, as the documentation for the netCDF-Java project prior to version 6 only had one documentation set, but as of version 6 is has two.  One nice thing about this approach would be that the presence of one or the other (`docURL` or `docURLs`) would tell if the project has multiple docsets or not, which might be useful.

## Potential Tasks

- [x] Rename json file containing version information from `projectName_doc_versions.json` to `version-info.json`
- [x] Request json file from root path rather than relative to page (`/projectName/version-info.json` instead of `../../version-info.json`.
- [x] Decide how to handle multiple docsets in the version selector

@ddirks - thoughts on all of this?

**Comment by ddirks** [comment]
Hi @lesserwhirls! Some initial thoughts:

1. Different file name for the json file: sure, why not. I tend to default to more descriptive file names but that can go overboard.
2. Requesting the json file from the root path: this was the original design. I remember there being a rationale for changing it to use the relative path, but I don't recall what it was off the top of my head.
3. Multiple docsets: I like the idea of generalizing to `docURLs` here. I might even suggest extending the json structure you've outlined in the netcdf-java/version-info.json file to include some other useful bits of information that can be used when populating the version selector. For example:

```
    {
      "version" : "6.0 (dev)",
      "include" : 1,
      "docURLs": {
        "userguide": {
            "baseURL": "https://docs.unidata.ucar.edu/netcdf-java/6.0/userguide/index.html",
            "docsetName": "netCDF-Java User's Guide"
        },   
        "developer": {
            "baseURL": "https://docs.unidata.ucar.edu/netcdf-java/6.0/developer/index.html",
            "docsetName": "netCDF-Java Developer's Guide"
        }
      }

```   
Note that the code that consumes the json file could iterate through the docURLs by index, so it wouldn't have to be aware of how many docsets there are or their names.

As an aside, I'd advocate for leaving package name information in the version-info.json file, for easy access once the code has cracked it to build the menu.

**Comment by lesserwhirls** [comment]
> 1. Different file name for the json file: sure, why not. I tend to default to more descriptive file names but that can go overboard.

For this particular file, I'm more on the side of the keep it simple side since we can represent everything related to the package version in the one file.

> 2. Requesting the json file from the root path: this was the original design. I remember there being a rationale for changing it to use the relative path, but I don't recall what it was off the top of my head.

It's possible that I was being silly thinking "if we do relative then it will work using the docs.unidata.ucar.edu domain as well as the artifacts.unidata.ucar.edu domain", but that's silly because cross-site scripting issues won't allow the site to render correctly anyways, so it's all good. I say we just reference from the root and say "heck it, docs must be viewed from the docs domain."

> 3. Multiple docsets: I like the idea of generalizing to `docURLs` here. I might even suggest extending the json structure you've outlined in the netcdf-java/version-info.json file to include some other useful bits of information that can be used when populating the version selector. For example:
>
>  <snip>
>
> Note that the code that consumes the json file could iterate through the docURLs by index, so it wouldn't have to be aware of how many docsets there are or their names.

Ok, so if a project does not use the concept of a docset...for example, cdm:

<https://docs.unidata.ucar.edu/thredds/cdm/4.0/index.html>

What would that look like? Something like this?

~~~json
{
  "package": "cdm",
  "packageName": "cdm",
  "releases": [{
    "version": "4.0",
    "include": 1,
    "docURLs": {
      "": {
        "baseURL": "https://docs.unidata.ucar.edu/thredds/cdm/4.0/index.html",
        "docsetName": "The Unidata Common Data Model"
      }
    }
  }]
}
~~~

> 
> As an aside, I'd advocate for leaving package name information in the version-info.json file, for easy access once the code has cracked it to build the menu.

I'm cool with leaving in the package name info stuff. But, combining that with the CDM example above (which, like NCML, is more spec like in nature), what does "package" mean? Also, if (like in my netCDF-Java example file at <https://docs.unidata.ucar.edu/netcdf-java/version-info.json>) we include "dev" versions, does using "releases" make sense as a key?

Sorry for muddying the waters here.

**Comment by ddirks** [comment]
So, am I correct in assuming that any package/project (however we define that here) that has one of these files will have *some* documentation? Whether or not there is more than one "docset"? (And whether or not we reveal it on the docs.unidata server?) If so, I think a single structure works for all cases.

I get your point about the word "package." I would be comfortable overloading the name to include things like CDM and NCML that may not be stand-alone things, but which are self-contained in the sense that they have their own space on nexus. Or we could choose another term ("module?"). 

RE: dev versions and such:
The original .json file definition included "status" and "date" information. I would shy away from having to parse the version string to look for annotations like "(dev)" and handle them -- we're already parsing a json file, why not just build the information we want in there?

So, as an example:

```
{
  "package": "cdm",
  "packageName": "cdm",
  "releases": [{
    "version": "4.0",
    "include": 1,
    "status" : "current" # or "beta", "dev", etc?
    "date" : "2021-04-29" # Useful when alerting users they are looking at older doc maybe?
    "docset": {
      "cdm": {
        "baseURL": "https://docs.unidata.ucar.edu/thredds/cdm/4.0/index.html",
        "docsetName": "The Unidata Common Data Model"
      }
    }
  }]
}
```

It's true, including "status" in this file means the field gets edited when a new release comes out (making it no longer "beta" or "current" or whatever). But the file has to be edited to include new entries, so maybe that's not a big deal?

Regarding a "date" field: I can see including this if we start displaying an alert when someone browses to a non-current version of the docs. ("Your viewing documentation for version 3.0. Version 3.1 was released in October 2019.")

More mud for the stream, sorry...

**Comment by lesserwhirls** [comment]
> So, am I correct in assuming that any package/project (however we define that here) that has one of these files will have _some_ documentation?  Whether or not there is more than one "docset"? (And whether or not we reveal it on the docs.unidata server?) If so, I think a single structure works for all cases.

In my mental model, this file belongs to the documentation as a whole, which can be made up of one or more sets of documentation (docsets), so if there is no documentation there is no file.

> I get your point about the word "package." I would be comfortable overloading the name to include things like CDM and NCML that may not be stand-alone things, but which are self-contained in the sense that they have their own space on nexus. Or we could choose another term ("module?").

I think  eventually the NcML documentation will be standalone (a specification only repository on github with its own documentation based on what we have now). Another one to think about would be the netCDF User Guide, which would just be  one docset.

> 
> RE: dev versions and such:
> The original .json file definition included "status" and "date" information. I would shy away from having to parse the version string to look for annotations like "(dev)" and handle them -- we're already parsing a json file, why not just build the information we want in there?
>
> So, as an example:
> 
> <snip>
> It's true, including "status" in this file means the field gets edited when a new release comes out (making it no longer "beta" or "current" or whatever). But the file has to be edited to include new entries, so maybe that's not a big deal?

I think that makes sense.

Updating my single docset example from my previous comment, we'd now have something like:

~~~json
{
  "package": "cdm",
  "packageName": "cdm",
  "releases": [{
    "version": "4.0",
    "status" : "current"
    "date" : "2021-04-29"
    "include": 1,
    "docURLs": {
      "": {
        "baseURL": "https://docs.unidata.ucar.edu/thredds/cdm/4.0/index.html",
        "docsetName": "The Unidata Common Data Model"
      }
    }
  }]
}
~~~

> Regarding a "date" field: I can see including this if we start displaying an alert when someone browses to a non-current version of the docs. ("Your viewing documentation for version 3.0. Version 3.1 was released in October 2019.")
> 
> More mud for the stream, sorry...

I liked date until I used it and had to think what it meant. Because I version the netCDF-Java docs with `major.minor`, it means the docs can update between point releases, so the date would change but the version would stay the same? Maybe there should be a distinction between package version and documentation version? (more mud!)

**Comment by lesserwhirls** [comment]
Ok, so after meeting up with @ddirks and @oxelson, we've come up with this:


_version_info.json_
~~~json
{
  "package" : "package-name",
  "packageName" : "human readable package name",
  "releases": RELEASE_ITEMS
}
~~~

| Key                    | Value Description                        | Type     | Required? | Example |
| ----------------- | ----------------------------------- | -------- | ----------- | --------- |
| `package`           | package name                             | `string` | yes           | ncml |
| `packageName` | human readable package name  | `string` | yes           | NetCDF Markup Language |
| `releases`           | `RELEASE_ITEMS` *details below* | `array`  | yes           | *details below* |

`RELEASE_ITEMS` is an array of  `RELEASE_ITEM` objects, and at least one is **required**. Each `RELEASE_ITEM` object looks like: 

~~~json
{
  "version" : "major.minor.point",
  "include" : int,
  "releaseDate": "2021-05-06",
  "status" : "version status",
  "docsets": DOCSET_ITEMS
}  
~~~

| Key               | Value Description                                                                              | Type    | Required? | Example |
| -------------- | ----------------------------------------------------------------------- | -------- | ----------- | ----------|
| `version`        | version associated with the documentation                                     | `string` | yes           | "5.4.1"  |
| `include`        | show `RELEASE_ITEM` in version selector widget ( `0=no`, `1=yes`) | `int`      | yes           | 1 |
| `releaseDate` | Date of package release                                                                   | `date`   | no            | "2021-04-25" |
| `status`          | description of the release status                                                       | `string` | no            | "current", "dev", "beta", "rc", "stable", etc. |
| `docsets`       | `DOCSET_ITEMS` *details below*                                                      | `object` | yes          | *details below* |

`DOCSET_ITEMS` is an object consisting of at least one  `DOCKSET_KEY: DOCSET_ITEM` pairs:

~~~json
{
  DOCKSET_KEY1: DOCSET_ITEM_1,
  DOCKSET_KEY2: DOCSET_ITEM_2,
  DOCKSET_KEY2: DOCSET_ITEM_N
}
~~~

The `DOCKSET_KEY` is a string (no spaces) used to identify a unique type of docset across multiple versions, where a docset is a distinct set of documentation, such as a User's Guide, a Developer's Guide, a Quick Start guide, etc. Each `DOCSET_ITEM` object looks like:

~~~json
{
  "baseUrl": "URL of the documentation set landing page",
  "docsetName": "Title of Docset 1"
}
~~~

| Key                 | Value Description                                                    | Type  | Required? | Example |
| --------------- | ------------------------------------------------------ | ------- | ---------- | --------- |
| `baseUrl`         | URL of the documentation set landing page         | `string` | yes         | "https://docs.unidata.ucar.edu/project/1.2.3/docset/index.html" |
| `docsetName` | Human readable name of the documentation set | `string` | yes          | "User's Guide"  |


Full example:

_version_info.json_
~~~json
{
  "package": "netcdf-java",
  "packageName": "netCDF-Java",
  "releases": [
    {
      "version" : "5.3.1",
      "include" : "0",
      "releaseDate": "2020-04-29",
      "docsets": {
        "userguide": {
          "baseUrl": "https://docs.unidata.ucar.edu/netcdf-java/5.3/userguide/index.html",
          "docsetName": "User's Guide"
        }
      }
    },
    {
      "version" : "5.3.3",
      "include" : "1",
      "releaseDate": "2020-06-18",
      "docsets": {
        "userguide": {
          "baseUrl": "https://docs.unidata.ucar.edu/netcdf-java/5.3/userguide/index.html",
          "docsetName": "User's Guide"
        }
      }
    },
    {
      "version" : "5.4.1",
      "status": "current",
      "releaseDate": "2020-12-17",
      "include" : 1,
      "docsets": {
        "userguide": {
          "baseUrl": "https://docs.unidata.ucar.edu/netcdf-java/5.4/userguide/index.html",
          "docsetName": "User's Guide"
        }
      }
    },
    {
      "version" : "6.0.0",
      "status" : "dev",
      "include" : 1,
      "docsets": {
        "userguide": {
          "baseUrl": "https://docs.unidata.ucar.edu/netcdf-java/6.0/userguide/index.html",
          "docsetName": "User's Guide"
        },
        "developer": {
          "baseUrl": "https://docs.unidata.ucar.edu/netcdf-java/6.0/developer/index.html",
          "docsetName": "Developer's Guide"
        }
      }
    }
  ]
}
~~~

**Comment by ddirks** [comment]
My only remaining questions are:

- Do we need to be nitpicky about the specification of the format of the date string? I think this is just documentation...
- RELEASE_ITEM.status is the only non-required key. Is it easier to simply say all keys are required but can have null values? This would (very slightly) simplify the code that consumes this value and also sidestep the potential problem of someone copying a file that omits that key and not realizing it exists. I don't feel strongly about this, just asking.

**Comment by lesserwhirls** [comment]
> My only remaining questions are:
> 
> * Do we need to be nitpicky about the specification of the format of the date string? I think this is just documentation...

Yeah, I think you're right - we'll leave the format out :-)

> * RELEASE_ITEM.status is the only non-required key. Is it easier to simply say all keys are required but can have null values? This would (very slightly) simplify the code that consumes this value and also sidestep the potential problem of someone copying a file that omits that key and not realizing it exists. I don't feel strongly about this, just asking.

I think that makes sense. I'll add one more update below.

**Comment by lesserwhirls** [comment]
_Note: All keys are required._

_version_info.json_
~~~json
{
  "package" : "package-name",
  "packageName" : "human readable package name",
  "releases": RELEASE_ITEMS
}
~~~

| Key                    | Value Description                        | Type     | Example |
| ----------------- | ----------------------------------- | -------- | --------- |
| `package`           | package name                             | `string` | ncml |
| `packageName` | human readable package name  | `string` | NetCDF Markup Language |
| `releases`           | `RELEASE_ITEMS` *details below* | `array`  | *details below* |

`RELEASE_ITEMS` is an array of  `RELEASE_ITEM` objects, and at least one is **required**. Each `RELEASE_ITEM` object looks like: 

~~~json
{
  "version" : "major.minor.point",
  "include" : int,
  "releaseDate": "2021-05-06",
  "status" : "version status",
  "docsets": DOCSET_ITEMS
}  
~~~

| Key               | Value Description                                                                              | Type    | Example |
| -------------- | ----------------------------------------------------------------------- | -------- | ----------|
| `version`        | version associated with the documentation                                     | `string` | "5.4.1"  |
| `include`        | show `RELEASE_ITEM` in version selector widget ( `0=no`, `1=yes`) | `int`      | 1 |
| `releaseDate` | Date of package release                                                                   | `date`   | "2021-04-25" |
| `status`          | the development status of the release. Can be an empty string.     | `string` | "beta" |
| `docsets`       | `DOCSET_ITEMS` *details below*                                                      | `object` | *details below* |

`DOCSET_ITEMS` is an object consisting of at least one  `DOCKSET_KEY: DOCSET_ITEM` pairs:

~~~json
{
  DOCKSET_KEY1: DOCSET_ITEM_1,
  DOCKSET_KEY2: DOCSET_ITEM_2,
  DOCKSET_KEY2: DOCSET_ITEM_N
}
~~~

The `DOCKSET_KEY` is a string (no spaces) used to identify a unique type of docset across multiple versions, where a docset is a distinct set of documentation, such as a User's Guide, a Developer's Guide, a Quick Start guide, etc. Each `DOCSET_ITEM` object looks like:

~~~json
{
  "baseUrl": "URL of the documentation set landing page",
  "docsetName": "Title of Docset 1"
}
~~~

| Key                 | Value Description                                                    | Type   | Example |
| --------------- | ------------------------------------------------------ | ------- | --------- |
| `baseUrl`         | URL of the documentation set landing page         | `string` | "https://docs.unidata.ucar.edu/project/1.2.3/docset/index.html" |
| `docsetName` | Human readable name of the documentation set | `string` | "User's Guide"  |


Full example:

_version_info.json_
~~~json
{
  "package": "netcdf-java",
  "packageName": "netCDF-Java",
  "releases": [
    {
      "version" : "5.3.1",
      "status" : "",
      "include" : "0",
      "releaseDate": "2020-04-29",
      "docsets": {
        "userguide": {
          "baseUrl": "https://docs.unidata.ucar.edu/netcdf-java/5.3/userguide/index.html",
          "docsetName": "User's Guide"
        }
      }
    },
    {
      "version" : "5.3.3",
      "status" : "",
      "include" : "1",
      "releaseDate": "2020-06-18",
      "docsets": {
        "userguide": {
          "baseUrl": "https://docs.unidata.ucar.edu/netcdf-java/5.3/userguide/index.html",
          "docsetName": "User's Guide"
        }
      }
    },
    {
      "version" : "5.4.1",
      "status": "current",
      "releaseDate": "2020-12-17",
      "include" : 1,
      "docsets": {
        "userguide": {
          "baseUrl": "https://docs.unidata.ucar.edu/netcdf-java/5.4/userguide/index.html",
          "docsetName": "User's Guide"
        }
      }
    },
    {
      "version" : "6.0.0",
      "status" : "SNAPSHOT",
      "releaseDate": "2021-05-06",
      "include" : 1,
      "docsets": {
        "userguide": {
          "baseUrl": "https://docs.unidata.ucar.edu/netcdf-java/6.0/userguide/index.html",
          "docsetName": "User's Guide"
        },
        "developer": {
          "baseUrl": "https://docs.unidata.ucar.edu/netcdf-java/6.0/developer/index.html",
          "docsetName": "Developer's Guide"
        }
      }
    }
  ]
}
~~~
